[backdrop]
enabled = true

[bar.default]
start = [ "launcher", "workspaces", "cpu", "ram", "active_window" ]
center = [ "date", "clock" ]
end = [
    "audio_visualizer",
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "theme_mode",
    "brightness",
    "keyboard_layout",
    "battery",
    "control-center"
]
margin_edge = 8
margin_ends = 16
widget_spacing = 8

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 20

[brightness]
enable_ddcutil = true

[control_center]
sidebar = "full"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "audio"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "system"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[location]
address = "Vidnoe, Moscow oblast, Russia"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 24
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1317.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 957.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 192.0
    box_width = 384.0
    cx = 960.0
    cy = 276.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

[notification]
background_opacity = 1

[osd.kinds]
bluetooth = false
caffeine = false
dnd = false
keyboard_layout = false
power_profile = false
wifi = false

[plugins]
enabled = []

[shell]
app_icon_color = "tertiary"
avatar_path = "/home/mitchanx/Pictures/avatar.png"
niri_overview_type_to_launch_enabled = true
password_style = "random"
screen_time_enabled = true

    [shell.panel]
    clipboard_placement = "floating"
    control_center_placement = "floating"
    session_placement = "floating"
    wallpaper_placement = "floating"

[theme]
source = "builtin"
builtin = "Gruvbox"
mode = "dark"

[theme.templates]
builtin_ids = [ "foot", "gtk3", "gtk4", "niri", "qt" ]
community_ids = [ "zed", "zen" ]

[wallpaper]
directory = "/home/mitchanx/Pictures/Wallpapers"
transition = [ "fade" ]
transition_on_startup = true

    [wallpaper.automation]
    enabled = true

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false
